### ISSUE TITLE
nodes.cpp Compile failure on Debian 9.9 64 bit gcc

### ISSUE THREAD

**Issue by wd5m** [skiphansen/thelinkbox#1]
Hi Skip, When attempting to compile thelinkbox on Debian 9.9 64 Bit OS, I get a failure with the following messages. Note that I am using a copy of the current source from github, and used bootstrap.sh to configure.  I have been able to avoid this compile error by changing the linkbox/nodes.cpp code for the "char DTMF2CharLookup[]...." to be "unsigned char" instead of just "char". I'm no C programmer, but if that seems like a valid patch, perhaps you would like to apply it to the github source. I'll attached a modified copy of nodes.cpp  I have compiled this on Debian 9.9 and Debian 10.0 64 Bit virtual servers just to test. I'm running this on Debian 8.11 64 Bit VPS (k5mot.link) and one EchoIRLP node (stn7658)  with Debian 7.8 32 Bit.  IRLP is starting to test on Debian 10 with 64Bit, so wanted to see if we could run TLB too. I think theBridge is okay, but I haven't fully tested it on 9 or 10 64Bit. I'm attempting to move to TLB and just use it on everything.

Thanks! David M. WD5M

The compile error I see follows. Attached is a modified  (patched) nodes.cpp file in a zip container.

nodes.cpp:693:1: error: narrowing conversion of ‘129’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
 };
 ^
nodes.cpp:693:1: error: narrowing conversion of ‘130’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
nodes.cpp:693:1: error: narrowing conversion of ‘131’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
nodes.cpp:693:1: error: narrowing conversion of ‘145’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
nodes.cpp:693:1: error: narrowing conversion of ‘146’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
nodes.cpp:693:1: error: narrowing conversion of ‘147’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
make: *** [nodes.o] Error 1

[nodes.cpp.zip](https://github.com/skiphansen/thelinkbox/files/3369789/nodes.cpp.zip)

**Comment by skiphansen** [comment]
Hi David,

Yes, that certainly looks reasonable, thanks for the patch.  I'll apply it shortly.

**Comment by skiphansen** [comment]
Sorry for the delay, I got distracted.  I just applied your change and committed it.

Skip
