### ISSUE TITLE
ShowIPAddresses is the incorrect variable name in tlb.conf.sample

### ISSUE THREAD

**Issue by wd5m** [skiphansen/thelinkbox#4]
The tlb.conf.sample file includes "ShowIPAddresses" for a configuration variable. I'm pretty sure that should be "LogIPAddresses".

**Comment by skiphansen** [comment]
Correct you are, fixed!
BTW: I did a search of the entire tree to make sure I found all of the references and I found one in the OpenWRT support for "Little Blue" ... I had almost forgot that the OpenWRT stuff even existed!
73's Skip WB6YMH
